### ISSUE TITLE
Feature: Total Views and Hits per Category / Taxonomy

### ISSUE THREAD

**Issue by larsschafer** [ibericode/koko-analytics#126] opened 2021-07-04 09:44 UTC
requested here https://wordpress.org/support/topic/post-type-and-taxonomy-stats/

**Comment by arnelap** [comment] 2023-05-08 08:06
and here https://github.com/ibericode/koko-analytics/issues/126

**Comment by arnelap** [comment] 2023-05-08 08:08
duplicate of https://github.com/ibericode/koko-analytics/issues/62 , can be closed

**Comment by larsschafer** [comment] 2023-05-08 09:15
Wrong email address?

**Closed** 2023-10-25 18:24 UTC

**Comment by dannyvankooten** [comment] 2023-10-25 18:25
I'm just closing this issue to keep the GitHub issue list about issues and bugs only. We're still tracking this feature suggestion here: #212
