### ISSUE TITLE
Feature Request: Make js function `trackPageview` accessible from the outside

### ISSUE THREAD

**Issue by hirasso** [ibericode/koko-analytics#166] opened 2022-09-20 16:20 UTC
Hi there, Koko Analytics looks promising! 

I have a feature request: Right now, it is not possible to access `trackPageview` from the outside. This would be crucial in the context of a [SPA](https://en.wikipedia.org/wiki/Single-page_application). I think a single line at the end of your `script.js`, just before or after `trackPageview()`, could already fix this:

```js
window.koko_analytics.trackPageview = trackPageview;
```
Now every time the URL of and SPA would be changed (on `pushState`, `replaceState`, `popState`), it would be possible to notify Koko Analytics about it:
```js
window.history.pushState({}, null, 'my-new-url');
if( typeof window.koko_analytics.trackPageview === 'function' ) {
  window.koko_analytics.trackPageview();
}
```

**Comment by hirasso** [comment] 2022-09-21 11:42
Created a PR for this feature: #167

**Comment by dannyvankooten** [comment] 2022-09-21 13:02
Duplicate of #103 - closing this for administrational purposes (but keen on making this work!).

**Closed by dannyvankooten** 2022-09-21 13:02 UTC
